{
    "openapi":"3.0.2",
    "info": {
        "license": {
            "name": "MIT",
            "url": "https://github.com/TacEtarip/loscreadores/blob/main/LICENSE"
        },
        "contact": {
            "email": "hu3rtas@outlook.com",
            "name": "Luis Huertas"
        },
        "title":"Los Creadores, creador de prendas API",
        "version":"0.0.1",
        "description": "Rest API para el creador de prendas. UNDER DEVELOPMENT"
    },
    "servers": [
        {
            "url":"http://localhost:2000"
        }
    ],
    "tags": [
        {
            "name": "materiales",
            "description": "Manejar los materiales textiles."
        },
        {
            "name": "utilidades",
            "description": "Manejar utilidades."
        }
    ],
    "components": {
        "responses": {
            "500":{
                "description": "Ocurrio un error en el servidor",
                "content": {
                    "aplication/json":{
                        "schema": {
                            "type": "object",
                            "properties": {
                                "errorMSG": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "Error-401": {
                "description": "No exite un token de autorizaci√≥n valido"
            },
            "Error_400": {
                "description": "Datos enviados de manera erronea o duplicada.",
                "content": {
                    "aplication/json":{
                        "schema": {
                            "$ref": "#/components/schemas/error400"
                        }
                    }
                }
            },
            "Succes": {
                "description": "Exito al procesar request"
            }
        },
        "securitySchemes": {
            "JWT TOKEN ADMIN": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT #token #codUsuario #username #tipo"
            },
            "JWT TOKEN ALL": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT #token #codUsuario #username #tipo"
            }
        },
        "schemas": {
            "error": {
                "type": "object",
                "description": "Error General",
                "properties": {
                    "error": {
                        "type": "string",
                        "description": "Mensaje de error"
                    }
                }
            },
            "error401": {
                "type": "object",
                "description": "Error No Autorizado",
                "properties": {
                    "error": {
                        "type": "string",
                        "description": "Mensaje de error"
                    }
                }
            },
            "error400": {
                "type": "object",
                "description": "Request generada de manera incorrecta o datos repetidos",
                "properties": {
                    "error": {
                        "type": "string",
                        "description": "Mensaje de error"
                    }
                }
            },
            "color": {
                "type": "object",
                "required": ["hex_code", "nombre"],
                "properties": {
                    "codColor": {
                        "type": "number",
                        "description": "Codigo del color"
                    },
                    "hex_code": {
                        "type": "string",
                        "description": "Codigo hex del color"
                    },
                    "nombre": {
                        "type": "string",
                        "description": "Nombre del color"
                    }
                },
                "example": {
                    "subTipo": ["Respiradores 3M", "Filtros 3M", "Respiradores Master", "Mascarillas", "Respiradores Astara", "Retenedores para filtros"],
                    "name": "Pro. Respiratoria",
                    "date": "2021-01-14T20:04:04.125+00:00",
                    "codigo": "1610645929520",
                    "deleted": false,
                    "link": "img-1610645929520-1621997665489.png",
                    "subTipoLink": ["IMG-1622763250845.png", "img-1622747657121.png", "IMG-1622763288076.png", "IMG-1622763339734.png", "IMG-1631032975632.jpg", "IMG-1630012297019.jpg"],
                    "order": 1
                }
            },
            "usuario": {
                "required": ["esAdmin", "username"],
                "type": "object",
                "properties": {
                    "codUsuario": {
                        "type": "number"
                    },
                    "DNI": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "contrasena_enviada": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    },
                    "fecha_creacion": {
                        "type": "string"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "dado_alta": {
                        "type": "boolean"
                    },
                    "esAdmin": {
                        "type": "boolean"
                    }
                }
            },
            "persona_natural": {
                "required": ["DNI", "nombre", "apellido_uno", "apellido_dos", "fecha_nacimiento"],
                "type": "object",
                "properties": {
                    "DNI": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "apellido_uno": {
                        "type": "string"
                    },
                    "apellido_dos": {
                        "type": "string"
                    },
                    "fecha_nacimiento": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    },
                    "codInfoContacto": {
                        "type": "number"
                    },
                    "deleted": {
                        "type": "boolean"
                    }
                }
            },
            "info_contacto": {
                "type": "object",
                "required": ["codDistrito", "celular", "direccion_linea_uno", "correo_electronico"],
                "properties": {
                    "codInfoContacto": {
                        "type": "number"
                    },
                    "codDistrito": {
                        "type": "string"
                    },
                    "celular": {
                        "type": "string"
                    },
                    "direccion_linea_uno": {
                        "type": "string"
                    },
                    "direccion_linea_dos": {
                        "type": "string"
                    },
                    "codigo_postal": {
                        "type": "string"
                    },
                    "correo_electronico": {
                        "type": "string"
                    },
                    "ultima_ctualizacion": {
                        "type": "string",
                        "description": "ISO DATE"
                    },
                    "deleted": {
                        "type": "boolean"
                    }
                }
            },
            "distrito": {
                "type": "object",
                "required": ["codDistrito", "codProvincia", "codDepartamento", "nombre"],
                "properties": {
                    "codDistrito": {
                        "type": "string"
                    },
                    "codProvincia": {
                        "type": "string"
                    },
                    "codDepartamento": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    }
                }
            },
            "provincia": {
                "type": "object",
                "required": ["codProvincia", "codDepartamento", "nombre"],
                "properties": {
                    "codProvincia": {
                        "type": "string"
                    },
                    "codDepartamento": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    }
                }
            },
            "departamento": {
                "type": "object",
                "required": ["codDepartamento", "codPais", "nombre"],
                "properties": {
                    "codDepartamento": {
                        "type": "string"
                    },
                    "codPais": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    }
                }
            },
            "pais": {
                "type": "string",
                "required": ["codPais", "iso", "nombre", "nombre_show", "iso3", "numero_codigo", "codigo_telefono"],
                "properties": {
                    "codPais": {
                        "type": "string"
                    },
                    "iso": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "nombre_show": {
                        "type": "string"
                    },
                    "iso3": {
                        "type": "string"
                    },
                    "numero_codigo": {
                        "type": "number"
                    },
                    "codigo_telefono": {
                        "type": "number"
                    }
                }
            },
            "trabajo": {
                "type":"object",
                "required": ["titulo", "pago"],
                "properties": {
                    "codTrabajo": {
                        "type": "number"
                    },
                    "titulo": {
                        "type": "string"
                    },
                    "pago": {
                        "type": "number"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    },
                    "deleted": {
                        "type": "boolean"
                    }
                }
            },
            "tipo_material": {
                "type": "object",
                "required": ["nombre", "ultima_actualizacion", "deleted"],
                "properties": {
                    "codTipoMaterial": {
                        "type": "number"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "subTipos": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/sub_tipo_material"
                        }
                    }
                }
            },
            "sub_tipo_material": {
                "type": "object",
                "required": ["nombre", "ultima_actualizacion", "deleted"],
                "properties": {
                    "codSubTipoMaterial": {
                        "type": "number"
                    },
                    "nombreTipo": {
                        "type": "string"
                    },
                    "codTipoMaterial": {
                        "type": "number"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string",
                        "description": "ISO STRING"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "materiales": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/material"
                        }
                    }
                }
            },
            "material": {
                "type": "object",
                "required": ["nombre", "ultima_actualizacion", 
                    "deleted", "descripcion", "unidad_medida", 
                    "unidad_medida_uso"],
                "properties": {
                    "codMaterial": {
                        "type": "number"
                    },
                    "codSubTipoMaterial": {
                        "type": "number"
                    },
                    "nombreSubTipo": {
                        "type": "string"
                    },
                    "codTipoMaterial": {
                        "type": "number"
                    },
                    "nombreTipo": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string",
                        "description": "ISO STRING"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "descripcion": {
                        "type": "string"
                    },
                    "unidad_medida": {
                        "type": "string"
                    },
                    "unidad_medida_uso": {
                        "type": "string"
                    },
                    "variantes": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/material_definido"
                        }
                    }
                }
            },
            "material_definido": {
                "type": "object",
                "required": ["codColor", "codMarca", "precio_por_unidad", 
                    "descripcion", "deleted", "ultima_actualizacion", "nombre"],
                "properties": {
                    "codMaterialDefinido": {
                        "type": "number"
                    },
                    "codMaterial": {
                        "type": "number"
                    },
                    "nombreMaterial": {
                        "type": "string"
                    },
                    "codSubTipoMaterial": {
                        "type": "number"
                    },
                    "nombreSubTipo": {
                        "type": "string"
                    },
                    "codTipoMaterial": {
                        "type": "number"
                    },
                    "nombreTipo": {
                        "type": "string"
                    },
                    "codColor": {
                        "type": "number"
                    },
                    "codMarca": {
                        "type": "number"
                    },
                    "precio_por_unidad": {
                        "type": "number"
                    },
                    "descripcion": {
                        "type": "string"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "nombreColor": {
                        "type": "string"
                    },
                    "hex_code": {
                        "type": "string"
                    },
                    "nombreMarca": {
                        "type": "string"
                    },
                    "unidad_medida_uso": {
                        "type": "string"
                    },
                    "materialesProductos": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/material_fisico"
                        }
                    }
                }
            },
            "filtro_material_definido": {
                "type": "object",
                "required": ["codMaterial"],
                "properties": {
                    "codMaterial": {
                        "type": "number"
                    },
                    "codColor": {
                        "type": "number"
                    },
                    "codMarca": {
                        "type": "number"
                    },
                    "precioMin": {
                        "type": "number"
                    },
                    "precioMax": {
                        "type": "number"
                    },
                    "texto": {
                        "type": "string"
                    }
                }
            },
            "filtro_material_fisico": {
                "type": "object",
                "required": ["codMaterialDefinido"],
                "properties": {
                    "codMaterialDefinido": {
                        "type": "number"
                    },
                    "estado": {
                        "type": "number",
                        "enum": [1, 2, 3]
                    },
                    "codProveedor": {
                        "type": "number"
                    },
                    "desde_fecha": {
                        "type": "string"
                    },
                    "hasta_fecha": {
                        "type": "string"
                    }
                }
            },
            "material_fisico": {
                "type": "object",
                "required": ["codMaterialFisico", "codMaterialDefinido", "deleted", 
                    "ultima_actualizacion", "cantidad_original", "cantidad_gastada", "dia_de_ingreso"],
                "properties": {
                    "codMaterialFisico": {
                        "type": "number"
                    },
                    "codMaterialDefinido": {
                        "type": "number"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "ultima_actualizacion": {
                        "type": "string",
                        "description": "ISO STRING"
                    },
                    "cantidad_original": {
                        "type": "number"
                    },
                    "cantidad_gastada": {
                        "type": "number"
                    },
                    "dia_de_ingreso": {
                        "type": "string",
                        "description": "ISO STRING"
                    }
                }
            },
            "login": {
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "authToken": {
                "type": "object",
                "properties": {
                    "displayName": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string"
                    }
                }
            },
            "unidad_de_medida": {
                "type": "object",
                "required": ["codUnidadDeMedida", "nombre", "ultima_actualizacion"],
                "properties": {
                    "codUnidadDeMedida": {
                        "type": "string"
                    } ,
                    "nombre": {
                        "type": "string"
                    },
                    "ultima_actualizacion": {
                        "type": "string"
                    }
                }
            },
            "proveedor": {
                "type": "object",
                "required": ["activo", "deleted"],
                "properties": {
                    "codProveedor": {
                        "type": "number"
                    },
                    "rating": {
                        "type": "number"
                    },
                    "activo": {
                        "type": "boolean"
                    },
                    "deleted": {
                        "type": "boolean"
                    },
                    "DNI": {
                        "type": "string"
                    },
                    "RUC": {
                        "type": "string"
                    },
                    "nombrePersonaJuridica": {
                        "type": "string"
                    },
                    "nombrePersonaNatural": {
                        "type": "string"
                    }
                }
            },
            "marca": {
                "type": "object",
                "required": ["nombre"],
                "properties": {
                    "codMarca": {
                        "type": "string"
                    },
                    "nombre": {
                        "type": "string"
                    },
                    "logo": {
                        "type": "string"
                    },
                    "info_extra": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "security": [
        {
            "JWT TOKEN ALL": []
        }
    ],
    "paths": {
        "/materiales/getAllTipos": {
            "get": {
                "summary": "Obtener todos los tipos de material.",
                "tags": ["materiales"],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/tipo_material"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getTipo/{codTipoMaterial}": {
            "get": {
                "summary": "Obtener un tipo de material, con sus sub-tipos de material.",
                "tags": ["materiales"],
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "allowEmptyValue": false,
                        "name": "codTipoMaterial",
                        "schema": {
                            "type": "number",
                            "description": "Codigo del tipo de material requerido"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "$ref": "#/components/schemas/tipo_material"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/crearTipoMaterial": {
            "post": {
                "summary": "Crear un tipo de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "tipoNombre": {
                                       "type": "string"
                                   }
                               }
                            },
                            "example": {
                                "tipoNombre": "nuevo tipo de material"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoTipo": {
                                            "$ref": "#/components/schemas/tipo_material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/editarTipo": {
            "post": {
                "summary": "Editar un tipo de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "tipoNombre": {
                                       "type": "string"
                                   },
                                   "codTipoMaterial": {
                                       "type": "number"
                                   }
                               }
                            },
                            "example": {
                                "tipoNombre": "nuevo tipo de material",
                                "codTipoMaterial": 1
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoTipo": {
                                            "$ref": "#/components/schemas/tipo_material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getSubTipo/{codSubTipoMaterial}": {
            "get": {
                "summary": "Obtener un sub-tipo de material, con sus materiales.",
                "tags": ["materiales"],
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "allowEmptyValue": false,
                        "name": "codSubTipoMaterial",
                        "schema": {
                            "type": "number",
                            "description": "Codigo del sub-tipo de material requerido"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "$ref": "#/components/schemas/sub_tipo_material"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/crearSubTipoMaterial": {
            "post": {
                "summary": "Crear un sub-tipo de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "subTipoNombre": {
                                       "type": "string"
                                   },
                                   "codTipoMaterial": {
                                        "type": "number"
                                   }
                               }
                            },
                            "example": {
                                "subTipoNombre": "nuevo sub-tipo",
                                "codTipoMaterial": 1
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoSubTipo": {
                                            "$ref": "#/components/schemas/sub_tipo_material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/editarSubTipo": {
            "post": {
                "summary": "Editar un sub-tipo de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "tipoNombre": {
                                       "type": "string"
                                   },
                                   "codTipoMaterial": {
                                       "type": "number"
                                   }
                               }
                            },
                            "example": {
                                "tipoNombre": "nuevo sub-tipo de material",
                                "codTipoMaterial": 1
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoSubTipo": {
                                            "$ref": "#/components/schemas/sub_tipo_material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getMaterial/{codMaterial}": {
            "get": {
                "summary": "Obtener un material, con sus variantes.",
                "tags": ["materiales"],
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "allowEmptyValue": false,
                        "name": "codMaterial",
                        "schema": {
                            "type": "number",
                            "description": "Codigo del material requerido"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "$ref": "#/components/schemas/material"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/crearMaterial": {
            "post": {
                "summary": "Crear un material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "nombreMaterial": {
                                       "type": "string"
                                   },
                                   "codSubTipoMaterial": {
                                       "type": "number"
                                   },
                                   "descripcion": {
                                        "type": "string"
                                    },
                                    "unidad_medida": {
                                        "type": "string"
                                    },
                                    "unidad_medida_uso": {
                                        "type": "string"
                                    }
                               }
                            },
                            "example": {
                                "nombreMaterial": "nuevo material",
                                "codSubTipoMaterial": 1,
                                "descripcion": "una descripci√≥n",
                                "unidad_medida": "UND",
                                "unidad_medida_uso": "CMT"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoMaterial": {
                                            "$ref": "#/components/schemas/material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/editarMaterial": {
            "post": {
                "summary": "Editar un material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "nombreMaterial": {
                                       "type": "string"
                                   },
                                   "codMaterial": {
                                       "type": "number"
                                   },
                                   "descripcion": {
                                        "type": "string"
                                    },
                                    "unidad_medida": {
                                        "type": "string"
                                    },
                                    "unidad_medida_uso": {
                                        "type": "string"
                                    }
                               }
                            },
                            "example": {
                                "nombreMaterial": "nuevo material",
                                "codMaterial": 1,
                                "descripcion": "una descripci√≥n",
                                "unidad_medida": "UND",
                                "unidad_medida_uso": "CMT"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevoMaterial": {
                                            "$ref": "#/components/schemas/material"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getMaterialDefinido/{codMaterialDefinido}": {
            "get": {
                "summary": "Obtener una variante de material, con sus productos.",
                "tags": ["materiales"],
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "allowEmptyValue": false,
                        "name": "codMaterialDefinido",
                        "schema": {
                            "type": "number",
                            "description": "Codigo de la variante requerida"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "$ref": "#/components/schemas/material_definido"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/crearMaterialDefinido": {
            "post": {
                "summary": "Crear una variante de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "nombre": {
                                       "type": "string"
                                   },
                                   "codMaterial": {
                                       "type": "number"
                                   },
                                   "codColor": {
                                        "type": "number"
                                    },
                                    "codMarca": {
                                        "type": "number"
                                    },
                                    "precio_por_unidad": {
                                        "type": "number"
                                    },
                                    "descripcion": {
                                        "type": "string"
                                    }
                               }
                            },
                            "example": {
                                "nombre": "nombre variante",
                                "codMaterial": 1,
                                "codColor": 1,
                                "codMarca": 1,
                                "precio_por_unidad": 1,
                                "descripcion": "Una descripci√≥n"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevaVariante": {
                                            "$ref": "#/components/schemas/material_definido"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/editarMaterialDefinido": {
            "post": {
                "summary": "Editar una variante de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "nombre": {
                                       "type": "string"
                                   },
                                   "codMaterialDefinido": {
                                       "type": "number"
                                   },
                                   "codColor": {
                                        "type": "number"
                                    },
                                    "codMarca": {
                                        "type": "number"
                                    },
                                    "precio_por_unidad": {
                                        "type": "number"
                                    },
                                    "descripcion": {
                                        "type": "string"
                                    }
                               }
                            },
                            "example": {
                                "nombre": "nombre variante",
                                "codMaterialDefinido": 1,
                                "codColor": 1,
                                "codMarca": 1,
                                "precio_por_unidad": 1,
                                "descripcion": "Una descripci√≥n"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "nuevaVariante": {
                                            "$ref": "#/components/schemas/material_definido"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getVariantesMaterialFiltro": {
            "post": {
                "summary": "Filtrar lista de variantes de un material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "$ref": "#/components/schemas/filtro_material_definido"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "type": "array",
                                   "items": {
                                       "$ref": "#/components/schemas/material_definido"
                                   }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getMaterialFisicosFiltro": {
            "post": {
                "summary": "Filtrar lista de productos de una variantes de material.",
                "tags": ["materiales"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "$ref": "#/components/schemas/filtro_material_definido"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                   "type": "array",
                                   "items": {
                                       "$ref": "#/components/schemas/material_fisico"
                                   }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getColores": {
            "get": {
                "summary": "Obtener colores.",
                "tags": ["utilidades"],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/color"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/getColor/{codColor}": {
            "get": {
                "summary": "Obtener un color.",
                "tags": ["utilidades"],
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "allowEmptyValue": false,
                        "name": "codColor",
                        "schema": {
                            "type": "number",
                            "description": "Codigo del color."
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/color"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        },
        "/materiales/insertarColor": {
            "get": {
                "summary": "Obtener un color.",
                "tags": ["utilidades"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "aplication/json": {
                            "schema": {
                               "type": "object",
                               "properties": {
                                   "subTipoNombre": {
                                       "type": "string"
                                   },
                                   "codTipoMaterial": {
                                        "type": "number"
                                   }
                               }
                            },
                            "example": {
                                "subTipoNombre": "nuevo sub-tipo",
                                "codTipoMaterial": 1
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "mensaje": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/Error_400"
                    }
                }
            }
        }
    }
}

